'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IF_UsoMaquina
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="ipostep_vP.001sap0003.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_XPT_"& _ 
        "INB_WS_CALL_SYNC_XPT.ipo_proc", [Namespace]:="urn:ipostep_vP.001sap0003.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_"& _ 
        "XPT_INB_WS_CALL_SYNC_XPT.ipo_proc", ConfigurationName:="IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_S"& _ 
        "YNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc")>  _
    Public Interface ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z.UsoMaquina no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ZUsoMaquina(ByVal request As IF_UsoMaquina.ZUsoMaquinaRequest) As IF_UsoMaquina.ZUsoMaquinaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function ZUsoMaquinaAsync(ByVal request As IF_UsoMaquina.ZUsoMaquinaRequest) As System.Threading.Tasks.Task(Of IF_UsoMaquina.ZUsoMaquinaResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUsoMaquinaType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUsoMaquinaResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private getUsoMaquinaResultField() As GetUsoMaquinaResponseTypeRow
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Row", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property GetUsoMaquinaResult() As GetUsoMaquinaResponseTypeRow()
            Get
                Return Me.getUsoMaquinaResultField
            End Get
            Set
                Me.getUsoMaquinaResultField = value
                Me.RaisePropertyChanged("GetUsoMaquinaResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class GetUsoMaquinaResponseTypeRow
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private serieField As String
        
        Private itemNameField As String
        
        Private odometroField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property ItemName() As String
            Get
                Return Me.itemNameField
            End Get
            Set
                Me.itemNameField = value
                Me.RaisePropertyChanged("ItemName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Odometro() As String
            Get
                Return Me.odometroField
            End Get
            Set
                Me.odometroField = value
                Me.RaisePropertyChanged("Odometro")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZUsoMaquinaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public GetUsoMaquina As IF_UsoMaquina.GetUsoMaquinaType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsoMaquina As IF_UsoMaquina.GetUsoMaquinaType)
            MyBase.New
            Me.GetUsoMaquina = GetUsoMaquina
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZUsoMaquinaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public GetUsoMaquinaResponse As IF_UsoMaquina.GetUsoMaquinaResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsoMaquinaResponse As IF_UsoMaquina.GetUsoMaquinaResponseType)
            MyBase.New
            Me.GetUsoMaquinaResponse = GetUsoMaquinaResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procChannel
        Inherits IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procClient
        Inherits System.ServiceModel.ClientBase(Of IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc)
        Implements IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_UsoMaquina_ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZUsoMaquina(ByVal request As IF_UsoMaquina.ZUsoMaquinaRequest) As IF_UsoMaquina.ZUsoMaquinaResponse Implements IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZUsoMaquina
            Return MyBase.Channel.ZUsoMaquina(request)
        End Function
        
        Public Function ZUsoMaquina(ByVal GetUsoMaquina As IF_UsoMaquina.GetUsoMaquinaType) As IF_UsoMaquina.GetUsoMaquinaResponseType
            Dim inValue As IF_UsoMaquina.ZUsoMaquinaRequest = New IF_UsoMaquina.ZUsoMaquinaRequest()
            inValue.GetUsoMaquina = GetUsoMaquina
            Dim retVal As IF_UsoMaquina.ZUsoMaquinaResponse = CType(Me,IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZUsoMaquina(inValue)
            Return retVal.GetUsoMaquinaResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_UsoMaquina_ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZUsoMaquinaAsync(ByVal request As IF_UsoMaquina.ZUsoMaquinaRequest) As System.Threading.Tasks.Task(Of IF_UsoMaquina.ZUsoMaquinaResponse) Implements IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZUsoMaquinaAsync
            Return MyBase.Channel.ZUsoMaquinaAsync(request)
        End Function
        
        Public Function ZUsoMaquinaAsync(ByVal GetUsoMaquina As IF_UsoMaquina.GetUsoMaquinaType) As System.Threading.Tasks.Task(Of IF_UsoMaquina.ZUsoMaquinaResponse)
            Dim inValue As IF_UsoMaquina.ZUsoMaquinaRequest = New IF_UsoMaquina.ZUsoMaquinaRequest()
            inValue.GetUsoMaquina = GetUsoMaquina
            Return CType(Me,IF_UsoMaquina.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZUsoMaquinaAsync(inValue)
        End Function
    End Class
End Namespace
